volumes:
  rpcn-storage:
    driver: local
    driver_opts:
      # Use your preferred storage path here, it must already exist
      device: /home/$USER/rpcn_data
      o: bind
      type: none

services:
  rpcn:
    image: crecent/rpcn-loopy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - rpcn-storage
    # Only works on Linux currently
    network_mode: host
#    ports:
#      - "31313:31313"
#      - "3657:3657"
