name: Rust tests

on:
  workflow_call:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Run tests
        run: cargo test --release --verbose
